// Code generated by the Lingua Franca compiler from:
// file://home/jk/velodyne_plugin/lf-src/gazeboClient.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/jk/velodyne_plugin/lf-src/src-gen/gazeboClient"
#include "include/ctarget/ctarget.h"
#include "core/threaded/reactor_threaded.c"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
#include "core/port.h"
#include <gazebo/gazebo_config.h>
#include <gazebo/transport/transport.hh>
#include <gazebo/msgs/msgs.hh>
#include <gazebo/gazebo_client.hh>
int main(int argc, char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
void _lf_set_default_command_line_options() {}
// =============== START reactor class gazeboClient
typedef struct {
    struct self_base_t base;
    reaction_t _lf__reaction_0;
    trigger_t _lf__startup;
    reaction_t* _lf__startup_reactions[1];
} gazeboclient_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void gazeboclientreaction_function_0(void* instance_args) {
    gazeboclient_self_t* self = (gazeboclient_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    // Load gazebo as a client
    gazebo::client::setup(_argc, _argv);
    
    // Create our node for communication
    gazebo::transport::NodePtr node(new gazebo::transport::Node());
    node->Init();
    
    // Publish to the  velodyne topic
    gazebo::transport::PublisherPtr pub =
        node->Advertise<gazebo::msgs::Vector3d>("~/my_velodyne/vel_cmd");
    
    // Wait for a subscriber to connect to this publisher
    pub->WaitForConnection();
    
    // Create a a vector3 message
    gazebo::msgs::Vector3d msg;
    
    // Set the velocity in the x-component
    gazebo::msgs::Set(&msg, ignition::math::Vector3d(std::atof(_argv[1]), 0, 0));
    
    // Send the message
    pub->Publish(msg);
    
    // Make sure to shut everything down.
    gazebo::client::shutdown();
        
}
#include "include/ctarget/set_undef.h"
gazeboclient_self_t* new_gazeboClient() {
    gazeboclient_self_t* self = (gazeboclient_self_t*)_lf_new_reactor(sizeof(gazeboclient_self_t));
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = gazeboclientreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    return self;
}
// =============== END reactor class gazeboClient
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t* _lf_startup_reactions[1];
int _lf_startup_reactions_size = 1;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
trigger_t* _lf_action_for_port(int port_id) {
        return NULL;
}
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int _lf_tokens_with_ref_count_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_tokens_with_ref_count_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    gazeboclient_self_t* gazeboclient_self[1];
    // ***** Start initializing gazeboClient of class gazeboClient
    gazeboclient_self[0] = new_gazeboClient();
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    _lf_startup_reactions[_lf_startup_reactions_count++] = &gazeboclient_self[0]->_lf__reaction_0;
    gazeboclient_self[0]->_lf__reaction_0.deadline = NEVER;
    //***** End initializing gazeboClient
    // **** Start deferred initialize for gazeboClient
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of gazeboClient.
        gazeboclient_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of gazeboClient
    }
    // **** End of deferred initialize for gazeboClient
    // **** Start non-nested deferred initialize for gazeboClient
    // **** End of non-nested deferred initialize for gazeboClient
    // Connect inputs and outputs for reactor gazeboClient.
    // Set reaction priorities for ReactorInstance gazeboClient
    {
        gazeboclient_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 140737488355327 shifted left 16 bits.
        gazeboclient_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[1] = 
        {1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 1};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
}
void _lf_trigger_startup_reactions() {
    for (int i = 0; i < _lf_startup_reactions_size; i++) {
        if (_lf_startup_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_startup_reactions[i], -1);
        }
    }
}
void _lf_initialize_timers() {
}
void logical_tag_complete(tag_t tag_to_send) {
}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
void terminate_execution() {}
